In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
%matplotlib inline
#!pip install seaborn

In [4]:
from sklearn import tree
X = [[0, 0], [1, 2]]
y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, y)

In [5]:
print(clf.predict([[2., 2.]]))
print(clf.predict_proba([[2. , 2.]]))

[1]
[[0. 1.]]


In [6]:
clf.predict([[0.4, 1.2]])

array([1])

In [7]:
clf.predict_proba([[0.4, 1.2]])

array([[0., 1.]])

In [8]:
clf.predict_proba([[0, 0.2]])

array([[1., 0.]])